# Generated by Django 5.1.3 on 2026-05-17 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dostavljac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NacinPlacanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('aktivan', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Narucitelj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresa', models.CharField(blank=True, max_length=200)),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('oib', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('cijena_po_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kolicina_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('zaProdaju', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zaposlenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puno_ime', models.CharField(max_length=100)),
                ('datumZaposlenja', models.DateTimeField(auto_now_add=True)),
                ('statusRada', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrKreiranja', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('zaprimljena', 'Zaprimljena'), ('u_obradi', 'U obradi'), ('isporucena', 'Isporučena'), ('otkazana', 'Otkazana')], default='zaprimljena', max_length=20)),
                ('napomena', models.TextField(blank=True)),
                ('dostavljac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sirana.dostavljac')),
                ('nacin_placanja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sirana.nacinplacanja')),
                ('narucitelj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sirana.narucitelj')),
                ('zaposlenik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narudzbe', to='sirana.zaposlenik')),
            ],
        ),
        migrations.CreateModel(
            name='StavkaNarudzbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cijena_po_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popust_postotak', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('narudzba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='sirana.narudzba')),
                ('sir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sirana.sir')),
            ],
        ),
    ]
