# Generated by Django 5.1.3 on 2026-05-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NacinPlacanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('aktivan', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('cijena_po_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kolicina_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_narudzbe', models.CharField(max_length=20, unique=True)),
                ('naziv_kupca', models.CharField(max_length=100)),
                ('email_kupca', models.EmailField(blank=True, max_length=254)),
                ('adresa_kupca', models.CharField(blank=True, max_length=200)),
                ('telefon_kupca', models.CharField(blank=True, max_length=30)),
                ('oib_kupca', models.CharField(blank=True, max_length=11)),
                ('status', models.CharField(choices=[('zaprimljena', 'Zaprimljena'), ('u_obradi', 'U obradi'), ('isporucena', 'Isporučena'), ('otkazana', 'Otkazana')], default='zaprimljena', max_length=20)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('napomena', models.TextField(blank=True)),
                ('nacin_placanja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sirana.nacinplacanja')),
            ],
        ),
        migrations.CreateModel(
            name='StavkaNarudzbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cijena_po_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popust_postotak', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('narudzba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='sirana.narudzba')),
                ('sir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sirana.sir')),
            ],
        ),
    ]
