# Generated by Django 6.0.5 on 2026-05-17 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narudzba',
            name='dostavljac',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='dostave', to='sirana.zaposlenik'),
        ),
        migrations.AlterField(
            model_name='zaposlenik',
            name='statusRada',
            field=models.CharField(choices=[('zaposlen', 'Zaposlen'), ('nezaposlen', 'Nezaposlen')], default='zaposlen', max_length=100),
        ),
        migrations.DeleteModel(
            name='Dostavljac',
        ),
    ]
