# Generated by Django 5.1.3 on 2026-05-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirana', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narudzba',
            name='broj_narudzbe',
        ),
    ]
