# Generated by Django 5.1.3 on 2026-05-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirana', '0002_remove_narudzba_broj_narudzbe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narucitelj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('adresa', models.CharField(blank=True, max_length=200)),
                ('telefon_kupca', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zaposlenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('datumZaposlenja', models.DateTimeField(auto_now_add=True)),
                ('statusRada', models.CharField(max_length=100)),
            ],
        ),
    ]
