# Generated by Django 6.0.5 on 2026-05-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirana', '0002_alter_narudzba_dostavljac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narudzba',
            name='dostavljac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dostave', to='sirana.zaposlenik'),
        ),
    ]
