# Generated by Django 6.0.5 on 2026-05-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirana', '0003_alter_narudzba_dostavljac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stavkanarudzbe',
            name='cijena_po_kg',
        ),
    ]
