# Generated by Django 5.1.3 on 2026-05-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirana', '0003_narucitelj_zaposlenik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narudzba',
            old_name='datum',
            new_name='vrKreiranja',
        ),
    ]
