# Generated by Django 5.1.3 on 2026-05-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirana', '0004_rename_datum_narudzba_vrkreiranja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zaposlenik',
            old_name='ime',
            new_name='puno_ime',
        ),
        migrations.AddField(
            model_name='narudzba',
            name='zaposlenik',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='narudzbe', to='sirana.zaposlenik'),
            preserve_default=False,
        ),
    ]
