# Generated by Django 5.1.3 on 2026-05-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirana', '0005_rename_ime_zaposlenik_puno_ime_narudzba_zaposlenik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostavljac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='narudzba',
            name='dostavljac',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='sirana.dostavljac'),
            preserve_default=False,
        ),
    ]
