# Generated by Django 5.1.3 on 2026-05-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirana', '0006_dostavljac_narudzba_dostavljac'),
    ]

    operations = [
        migrations.AddField(
            model_name='sir',
            name='zaProdaju',
            field=models.BooleanField(default=True),
        ),
    ]
